version: "3"

services:
  apisix:
    image: apache/apisix:2.14.1-alpine
    volumes:
      - ./config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./yaml:/usr/local/apisix/apisix/discovery/yaml:ro
      - ./sample:/var/apisix:ro
    ports:
      - "9080:9080"
      - "9090:9090"
    restart: always
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.5.2
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"
    ports:
      - "2397:2397"
